"use server";

/**
 * PROJECT LANDING SYSTEM — CRM Actions
 *
 * Server actions for public-facing commercial events generated by the
 * Project Landing System. Intentionally isolated from lib/actions/leads.ts
 * to avoid coupling the public module to internal CRM internals.
 *
 * CRM strategy (Phase 1):
 * - Reuse the Lead model as-is (no schema migration needed).
 * - Store simulation metadata as structured JSON in Lead.notas.
 * - Field mapping: anticipo/cuota/plazo → notas JSON (SimulationCRMMetadata).
 * - Tag origin via Lead.origen = "SIMULADOR_LANDING" | "SIMULADOR_UNIDAD".
 * - Leave Lead.unidadInteres as optional string ID (existing pattern).
 *
 * Phase 2:
 * - Dedicated SimulationEvent model for richer analytics.
 * - LogicToop hook on origen = "SIMULADOR_*" for automation triggers.
 */

import { db } from "@/lib/db";
import { checkRateLimit, getClientIp } from "@/lib/rate-limit";
import { headers } from "next/headers";
import type { SimulationLeadPayload, SimulationCRMMetadata } from "./types";
import { executeLeadReception } from "@/lib/crm-pipeline";

// ─── Rate limit for public simulation submissions ─────────────────────────────
// 5 per IP per 10 minutes — more restrictive than general contact (intentional)
const SIMULATION_RATE_LIMIT = {
    limit: 5,
    windowMs: 10 * 60 * 1000,
    keyPrefix: "rl:sim:",
} as const;

// ─── Input validation (no Zod dep — keep it minimal and stable) ──────────────

function validateSimulationPayload(data: unknown): {
    ok: true;
    payload: SimulationLeadPayload;
} | { ok: false; error: string } {
    if (!data || typeof data !== "object") return { ok: false, error: "Payload inválido." };

    const d = data as Record<string, unknown>;

    if (!d.proyectoId || typeof d.proyectoId !== "string") return { ok: false, error: "proyectoId requerido." };
    if (!d.nombre || typeof d.nombre !== "string" || d.nombre.trim().length < 2) return { ok: false, error: "Nombre inválido." };
    if (!d.whatsapp || typeof d.whatsapp !== "string" || d.whatsapp.trim().length < 6) return { ok: false, error: "WhatsApp inválido." };
    if (typeof d.anticipoDisponible !== "number" || d.anticipoDisponible < 0) return { ok: false, error: "Anticipo inválido." };
    if (typeof d.cuotaMensualPosible !== "number" || d.cuotaMensualPosible < 0) return { ok: false, error: "Cuota mensual inválida." };
    if (d.anticipoDisponible === 0 && d.cuotaMensualPosible === 0) {
        return { ok: false, error: "Indicá al menos un anticipo disponible o una cuota mensual posible." };
    }
    if (typeof d.plazoMeses !== "number" || d.plazoMeses < 1) return { ok: false, error: "Plazo inválido." };

    return {
        ok: true,
        payload: {
            proyectoId: d.proyectoId,
            proyectoNombre: typeof d.proyectoNombre === "string" ? d.proyectoNombre : "",
            unidadId: typeof d.unidadId === "string" ? d.unidadId : undefined,
            unidadNumero: typeof d.unidadNumero === "string" ? d.unidadNumero : undefined,
            nombre: (d.nombre as string).trim(),
            whatsapp: (d.whatsapp as string).trim(),
            email: typeof d.email === "string" && d.email.trim() ? d.email.trim() : undefined,
            anticipoDisponible: d.anticipoDisponible,
            cuotaMensualPosible: d.cuotaMensualPosible,
            plazoMeses: d.plazoMeses,
            quiereVisita: d.quiereVisita === true,
            quiereWhatsApp: d.quiereWhatsApp === true,
            mensaje: typeof d.mensaje === "string" ? d.mensaje.trim() : undefined,
            origen: d.origen === "SIMULADOR_UNIDAD" ? "SIMULADOR_UNIDAD" : "SIMULADOR_LANDING",
            moneda: typeof d.moneda === "string" ? d.moneda : "USD",
        },
    };
}

// ─── Build structured notas JSON ──────────────────────────────────────────────

function buildCRMNotas(payload: SimulationLeadPayload): string {
    const metadata: SimulationCRMMetadata = {
        eventoTipo: "SIMULACION_FINANCIACION",
        anticipoDisponible: payload.anticipoDisponible,
        cuotaMensualPosible: payload.cuotaMensualPosible,
        plazoMeses: payload.plazoMeses,
        unidadId: payload.unidadId,
        unidadNumero: payload.unidadNumero,
        quiereVisita: payload.quiereVisita,
        quiereWhatsApp: payload.quiereWhatsApp,
        origen: payload.origen,
        moneda: payload.moneda,
        generadoEn: new Date().toISOString(),
    };

    const lines = [
        `[SIMULACIÓN COMERCIAL — ${payload.proyectoNombre}]`,
        `Anticipo disponible: ${payload.moneda} ${payload.anticipoDisponible.toLocaleString()}`,
        `Cuota mensual posible: ${payload.moneda} ${payload.cuotaMensualPosible.toLocaleString()}`,
        `Plazo deseado: ${payload.plazoMeses} meses`,
        payload.unidadNumero ? `Unidad de interés: #${payload.unidadNumero}` : null,
        payload.quiereVisita ? "Solicita coordinar visita: Sí" : null,
        payload.quiereWhatsApp ? "Prefiere contacto por WhatsApp: Sí" : null,
        payload.mensaje ? `Mensaje: ${payload.mensaje}` : null,
        `\n[metadata]\n${JSON.stringify(metadata)}`,
    ]
        .filter(Boolean)
        .join("\n");

    return lines;
}

// ─── Main Action ──────────────────────────────────────────────────────────────

export async function crearSimulacionFinanciacion(data: unknown): Promise<{
    success: boolean;
    error?: string;
    leadId?: string;
}> {
    // 1. Rate limit
    const ip = getClientIp(new Request("http://x", { headers: headers() }));
    const rl = await checkRateLimit(ip, SIMULATION_RATE_LIMIT);
    if (!rl.allowed) {
        return { success: false, error: "Demasiadas solicitudes. Intentá de nuevo en unos minutos." };
    }

    // 2. Validate
    const validation = validateSimulationPayload(data);
    if (!validation.ok) {
        return { success: false, error: validation.error };
    }
    const payload = validation.payload;

    // 3. Resolve orgId from project (needed for multi-tenant CRM routing)
    let orgId: string | null = null;
    try {
        const project = await db.proyecto.findUnique({
            where: { id: payload.proyectoId },
            select: { orgId: true, visibilityStatus: true, deletedAt: true },
        });

        if (!project || project.deletedAt || project.visibilityStatus !== "PUBLICADO") {
            return { success: false, error: "Proyecto no encontrado o no disponible." };
        }

        orgId = project.orgId;
    } catch {
        return { success: false, error: "Error al verificar el proyecto." };
    }

    // 4. Build notas with simulation metadata
    const notas = buildCRMNotas(payload);

    // 5. Build human-readable message for the lead
    const mensajeResumen = [
        `Simulación comercial para ${payload.proyectoNombre}.`,
        payload.unidadNumero ? `Interés en unidad #${payload.unidadNumero}.` : null,
        `Anticipo disponible: ${payload.moneda} ${payload.anticipoDisponible.toLocaleString()}.`,
        `Cuota mensual posible: ${payload.moneda} ${payload.cuotaMensualPosible.toLocaleString()}.`,
        `Plazo deseado: ${payload.plazoMeses} meses.`,
        payload.mensaje || null,
    ]
        .filter(Boolean)
        .join(" ");

    // 6. Upsert lead (by whatsapp within same org, to avoid duplicates)
    try {
        const existingLead = orgId
            ? await db.lead.findFirst({
                where: { telefono: payload.whatsapp, orgId },
                select: { id: true },
            })
            : null;

        let leadId: string;

        if (existingLead) {
            // Enrich existing lead with new simulation data (upsert strategy)
            await db.lead.update({
                where: { id: existingLead.id },
                data: {
                    proyectoId: payload.proyectoId,
                    unidadInteres: payload.unidadId ?? undefined,
                    origen: payload.origen,
                    mensaje: mensajeResumen,
                    notas,
                    updatedAt: new Date(),
                },
            });
            leadId = existingLead.id;
        } else {
            // New lead — ingest via central pipeline to guarantee:
            // AI scoring, opportunity creation, tenant workflows, LogicToop dispatch.
            const result = await executeLeadReception({
                nombre: payload.nombre,
                email: payload.email ?? null,
                telefono: payload.whatsapp,
                origen: payload.origen,
                canalOrigen: "WEB",
                proyectoId: payload.proyectoId,
                unidadInteres: payload.unidadId ?? null,
                mensaje: mensajeResumen,
                notas,
                orgId,
                estado: "NUEVO",
                sourceType: "LANDING",
                rawPayloadForIntake: payload
            });

            if (!result.success) {
                throw new Error(result.error || "Error al crear lead de simulación");
            }

            leadId = result.leadId!;
        }

        return { success: true, leadId };
    } catch (err) {
        console.error("[crearSimulacionFinanciacion] DB error:", err);
        return { success: false, error: "No se pudo registrar la propuesta. Intentá de nuevo." };
    }
}
