version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: seventoop-db
    restart: always
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=seventoop
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - seventoop-net

networks:
  seventoop-net:
    name: seventoop-net

volumes:
  db_data:
